"""Update inventory model for TikTok bot

Revision ID: 20260203_200000
Revises: 20260203_183047
Create Date: 2026-02-03 20:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '20260203_200000'
down_revision: Union[str, None] = '20260203_183047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to inventory table
    op.add_column('inventory', sa.Column('category', sa.Enum('CLOTHES', 'SHOES', name='productcategory'), nullable=True))
    op.add_column('inventory', sa.Column('tier', sa.Enum('BUDGET', 'MID_RANGE', 'PREMIUM', name='producttier'), nullable=True))
    op.add_column('inventory', sa.Column('brand', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('inventory', sa.Column('price_kes', sa.Integer(), nullable=True))
    op.add_column('inventory', sa.Column('negotiable', sa.Boolean(), nullable=True))
    op.add_column('inventory', sa.Column('tag_size', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    op.add_column('inventory', sa.Column('fit_notes', sa.Text(), nullable=True))
    
    # Create indexes for new columns
    op.create_index(op.f('ix_inventory_category'), 'inventory', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_tier'), 'inventory', ['tier'], unique=False)
    op.create_index(op.f('ix_inventory_price_kes'), 'inventory', ['price_kes'], unique=False)
    op.create_index(op.f('ix_inventory_brand'), 'inventory', ['brand'], unique=False)
    
    # Drop old columns that are being replaced
    op.drop_index('ix_inventory_price', table_name='inventory')
    op.drop_column('inventory', 'price')
    op.drop_column('inventory', 'size_label')  # Replaced by tag_size
    
    # Make new columns non-nullable after migration (for existing data, set defaults)
    op.execute("UPDATE inventory SET category = 'CLOTHES' WHERE category IS NULL")
    op.execute("UPDATE inventory SET tier = 'MID_RANGE' WHERE tier IS NULL")
    op.execute("UPDATE inventory SET price_kes = 0 WHERE price_kes IS NULL")
    op.execute("UPDATE inventory SET negotiable = FALSE WHERE negotiable IS NULL")
    op.execute("UPDATE inventory SET tag_size = 'M' WHERE tag_size IS NULL")
    op.execute("UPDATE inventory SET fit_notes = 'Standard fit.' WHERE fit_notes IS NULL")
    
    # Alter columns to non-nullable
    op.alter_column('inventory', 'category', nullable=False)
    op.alter_column('inventory', 'tier', nullable=False)
    op.alter_column('inventory', 'price_kes', nullable=False)
    op.alter_column('inventory', 'negotiable', nullable=False)
    op.alter_column('inventory', 'tag_size', nullable=False)
    op.alter_column('inventory', 'fit_notes', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back old columns
    op.add_column('inventory', sa.Column('price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.add_column('inventory', sa.Column('size_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    
    # Create old indexes
    op.create_index('ix_inventory_price', 'inventory', ['price'], unique=False)
    
    # Drop new indexes
    op.drop_index(op.f('ix_inventory_brand'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_price_kes'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_tier'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_category'), table_name='inventory')
    
    # Drop new columns
    op.drop_column('inventory', 'fit_notes')
    op.drop_column('inventory', 'tag_size')
    op.drop_column('inventory', 'negotiable')
    op.drop_column('inventory', 'price_kes')
    op.drop_column('inventory', 'brand')
    op.drop_column('inventory', 'tier')
    op.drop_column('inventory', 'category')
    
    # ### end Alembic commands ###
