"""Fix enum columns to string

Revision ID: 20260204_090000
Revises: 20260203_200000
Create Date: 2026-02-04 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '20260204_090000'
down_revision: Union[str, None] = '20260203_200000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop indexes on enum columns
    op.drop_index('ix_inventory_category', table_name='inventory')
    op.drop_index('ix_inventory_tier', table_name='inventory')
    op.drop_index('ix_inventory_status', table_name='inventory')
    
    # Alter columns from enum to varchar
    op.alter_column('inventory', 'category',
               existing_type=sa.Enum('CLOTHES', 'SHOES', name='productcategory'),
               type_=sa.String(length=20),
               existing_nullable=False)
    
    op.alter_column('inventory', 'tier',
               existing_type=sa.Enum('BUDGET', 'MID_RANGE', 'PREMIUM', name='producttier'),
               type_=sa.String(length=20),
               existing_nullable=False)
    
    op.alter_column('inventory', 'status',
               existing_type=sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', name='inventorystatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    
    # Recreate indexes
    op.create_index(op.f('ix_inventory_category'), 'inventory', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_tier'), 'inventory', ['tier'], unique=False)
    op.create_index(op.f('ix_inventory_status'), 'inventory', ['status'], unique=False)
    
    # Drop enum types
    sa.Enum('CLOTHES', 'SHOES', name='productcategory').drop(op.get_bind(), checkfirst=True)
    sa.Enum('BUDGET', 'MID_RANGE', 'PREMIUM', name='producttier').drop(op.get_bind(), checkfirst=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum types
    sa.Enum('CLOTHES', 'SHOES', name='productcategory').create(op.get_bind(), checkfirst=True)
    sa.Enum('BUDGET', 'MID_RANGE', 'PREMIUM', name='producttier').create(op.get_bind(), checkfirst=True)
    
    # Drop indexes
    op.drop_index(op.f('ix_inventory_status'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_tier'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_category'), table_name='inventory')
    
    # Alter columns back to enum
    op.alter_column('inventory', 'status',
               existing_type=sa.String(length=20),
               type_=sa.Enum('AVAILABLE', 'RESERVED', 'SOLD', name='inventorystatus'),
               existing_nullable=False)
    
    op.alter_column('inventory', 'tier',
               existing_type=sa.String(length=20),
               type_=sa.Enum('BUDGET', 'MID_RANGE', 'PREMIUM', name='producttier'),
               existing_nullable=False)
    
    op.alter_column('inventory', 'category',
               existing_type=sa.String(length=20),
               type_=sa.Enum('CLOTHES', 'SHOES', name='productcategory'),
               existing_nullable=False)
    
    # Recreate indexes
    op.create_index(op.f('ix_inventory_category'), 'inventory', ['category'], unique=False)
    op.create_index(op.f('ix_inventory_tier'), 'inventory', ['tier'], unique=False)
    op.create_index(op.f('ix_inventory_status'), 'inventory', ['status'], unique=False)
    
    # ### end Alembic commands ###
